name: fno-helmholtz
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy # Tested with 1.19.2
  - pytorch # 1.7.1
  - cudatoolkit=11.0.221
  - pandas # 1.2.1
  - scikit-learn # 0.23.2
  - matplotlib # 3.3.2
  - tqdm # 4.55.1
  - ray # 1.4.1 - or install via pip install ray[default]
  - wandb # 0.11.2
  - scikit-optimize # 0.8.1
  - jupyterlab # 3.2.4